Add don't configure vm option to boot-seed-vm
In CI testing, the environment in libvirt will already exist, adding
the -f option for testing to indicate this and so it doesn't run
the virsh commands.

Still defaults to being configured.

Change-Id: If5c156c833509b2774e3e6c775498a4f84d8442b

diff --git a/scripts/boot-seed-vm b/scripts/boot-seed-vm
--- a/scripts/boot-seed-vm
+++ b/scripts/boot-seed-vm
@@ -28,6 +28,7 @@ BRIDGE=brbm
 export IMAGE_NAME=seed
 IMAGE_CACHE_DIR=${IMAGE_CACHE_DIR:-~/.cache/image-create/image-file-cache}
 export DIB_IMAGE_SIZE=30
+CONFIGURE_VM=yes
 START_VM=yes
 ALWAYS_ELEMENTS='vm local-config stackuser boot-stack nova-baremetal seed-stack-config remove-serial-console'
 EXTRA_ELEMENTS=${EXTRA_ELEMENTS:-cloud-init-nocloud}
@@ -50,11 +51,12 @@ function show_options () {
     echo "                       (defaults to kvm if available, otherwise qemu)"
     echo "      -c            -- use a image cache for seed image"
     echo "      -n            -- don't automatically start the VM"
+    echo "      -f            -- don't automatically configure the VM"
     echo
     exit 0
 }
 
-TEMP=`getopt -o hcna:o:s:b:e: -n $SCRIPT_NAME -- "$@"`
+TEMP=`getopt -o hcnfa:o:s:b:e: -n $SCRIPT_NAME -- "$@"`
 if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
 # Note the quotes around `$TEMP': they are essential!
@@ -70,6 +72,7 @@ while true ; do
         -h) show_options;;
         -c) export IMAGE_CACHE_USE=1; shift ;;
         -n) export START_VM=; shift ;;
+        -f) export CONFIGURE_VM=; shift ;;
         --) shift ; break ;;
         *) echo "Error: unsupported option $1." ; exit 1 ;;
     esac
@@ -108,11 +111,13 @@ if [ ! -e $DIB ]; then
     exit 1
 fi
 
-# Destroy pre-existing VM of the same name
+# If we're setting up a new environment, destroy pre-existing VM of the same name
 # but ignore any errors if one doesn't exist
-which virsh >/dev/null || die "Error: virsh not found in path"
-sudo virsh destroy  $IMAGE_NAME 2>/dev/null || echo "$IMAGE_NAME VM not running"
-sudo virsh undefine $IMAGE_NAME 2>/dev/null || echo "$IMAGE_NAME VM not defined"
+if [ $CONFIGURE_VM ]; then
+    which virsh >/dev/null || die "Error: virsh not found in path"
+    sudo virsh destroy  $IMAGE_NAME 2>/dev/null || echo "$IMAGE_NAME VM not running"
+    sudo virsh undefine $IMAGE_NAME 2>/dev/null || echo "$IMAGE_NAME VM not defined"
+fi
 
 mkdir -p $IMAGE_CACHE_DIR
 IMAGE_CACHE_FILE=$IMAGE_CACHE_DIR/$(echo $ARCH $ALWAYS_ELEMENTS $EXTRA_ELEMENTS | sha1sum | awk '{ print $1 }' )
@@ -128,7 +133,8 @@ sudo cp $IMAGE_CACHE_FILE.qcow2 /var/lib/libvirt/images/$IMAGE_NAME.qcow2
 
 sudo chattr +C /var/lib/libvirt/images/$IMAGE_NAME.qcow2 || true
 
-configure-vm \
+if [ $CONFIGURE_VM ]; then
+    configure-vm \
            --name $IMAGE_NAME \
            --image /var/lib/libvirt/images/$IMAGE_NAME.qcow2 \
            --baremetal-interface $BRIDGE \
@@ -136,6 +142,7 @@ configure-vm \
            --arch $SEED_ARCH \
            --libvirt-nic-driver $LIBVIRT_NIC_DRIVER \
 	   --seed
+fi
 
 function poll_vm {
   MAC=$(sudo virsh dumpxml $IMAGE_NAME | grep "mac address" | head -1 | awk -F "'" '{print $2}')
