boot-seed-vm: allow multiple ELEMENTS_PATH items
Updates boot-seed-vm so that it supports ELEMENTS_PATH when
more than one item/entry is in the path.

Change-Id: I94aa90509d38d7e1eb758b5a03feb57af6c15764

diff --git a/scripts/boot-seed-vm b/scripts/boot-seed-vm
--- a/scripts/boot-seed-vm
+++ b/scripts/boot-seed-vm
@@ -94,10 +94,16 @@ case $ARCH in
 esac
 
 ELEMENTS_PATH=${ELEMENTS_PATH:-$SCRIPT_HOME/../../tripleo-image-elements/elements}
-if [ ! -d $ELEMENTS_PATH ]; then
-    echo "Error: unable to locate elements path at $ELEMENTS_PATH"
-    exit 1
-fi
+OLD_IFS=$IFS
+IFS=:
+for EPATH in  $ELEMENT_PATH; do
+  if [ ! -d $EPATH ]; then
+      echo "Error: unable to locate elements path at $EPATH"
+      exit 1
+  fi
+done
+IFS=$OLD_IFS
+
 export ELEMENTS_PATH
 
 DIB_PATH=${DIB_PATH:-$SCRIPT_HOME/../../diskimage-builder}
