Add image already exists option to boot-seed-vm
Add an option to indicate that the image to be used does not need
to be built at this stage.

This differs from a cached image that lives on the disk during
this step.

Change-Id: I0672e2ae20e81b9edef328cc6f71a2a32e8b4707

diff --git a/scripts/boot-seed-vm b/scripts/boot-seed-vm
--- a/scripts/boot-seed-vm
+++ b/scripts/boot-seed-vm
@@ -29,6 +29,7 @@ export IMAGE_NAME=seed
 IMAGE_CACHE_DIR=${IMAGE_CACHE_DIR:-~/.cache/image-create/image-file-cache}
 export DIB_IMAGE_SIZE=30
 CONFIGURE_VM=yes
+CREATE_IMAGE=yes
 START_VM=yes
 ALWAYS_ELEMENTS='vm local-config stackuser boot-stack nova-baremetal seed-stack-config remove-serial-console'
 EXTRA_ELEMENTS=${EXTRA_ELEMENTS:-cloud-init-nocloud}
@@ -52,13 +53,15 @@ function show_options () {
     echo "                           (defaults to kvm if available, otherwise
                                      qemu)"
     echo "      -c                -- use a image cache for seed image"
+    echo "      -i                -- image file was built elsewhere, don't
+                                     create"
     echo "      -n                -- don't automatically start the VM"
     echo "      --use-existing-vm -- use existing VM"
     echo
     exit 0
 }
 
-TEMP=`getopt -o hcna:o:s:b:e: -l use-existing-vm -n $SCRIPT_NAME -- "$@"`
+TEMP=`getopt -o hcnai:o:s:b:e: -l use-existing-vm -n $SCRIPT_NAME -- "$@"`
 if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
 # Note the quotes around `$TEMP': they are essential!
@@ -74,6 +77,7 @@ while true ; do
         -h) show_options;;
         -c) export IMAGE_CACHE_USE=1; shift ;;
         -n) export START_VM=; shift ;;
+        -i) export CREATE_IMAGE=; shift ;;
         --use-existing-vm) export CONFIGURE_VM=; shift ;;
         --) shift ; break ;;
         *) echo "Error: unsupported option $1." ; exit 1 ;;
@@ -102,15 +106,19 @@ case $ARCH in
     *) echo "Unsupported arch $ARCH!" ; exit 1 ;;
 esac
 
-ELEMENTS_PATH=${ELEMENTS_PATH:-$SCRIPT_HOME/../../tripleo-image-elements/elements}
-export ELEMENTS_PATH
+if [ $CREATE_IMAGE  ]; then
 
-DIB_PATH=${DIB_PATH:-$SCRIPT_HOME/../../diskimage-builder}
-DIB=$(which disk-image-create || echo $DIB_PATH/bin/disk-image-create)
+    ELEMENTS_PATH=${ELEMENTS_PATH:-$SCRIPT_HOME/../../tripleo-image-elements/elements}
+    export ELEMENTS_PATH
 
-if [ ! -e $DIB ]; then
-    echo "Error: unable to locate disk-image-create"
-    exit 1
+    DIB_PATH=${DIB_PATH:-$SCRIPT_HOME/../../diskimage-builder}
+    DIB=$(which disk-image-create || echo $DIB_PATH/bin/disk-image-create)
+
+    if [ ! -e $DIB ]; then
+        echo "Error: unable to locate disk-image-create"
+        exit 1
+    fi
+
 fi
 
 # If we're setting up a new VM, destroy pre-existing VM of the same name
@@ -121,19 +129,22 @@ if [ $CONFIGURE_VM ]; then
     sudo virsh undefine $IMAGE_NAME 2>/dev/null || echo "$IMAGE_NAME VM not defined"
 fi
 
-mkdir -p $IMAGE_CACHE_DIR
-IMAGE_CACHE_FILE=$IMAGE_CACHE_DIR/$(echo $ARCH $ALWAYS_ELEMENTS $EXTRA_ELEMENTS | sha1sum | awk '{ print $1 }' )
+if [ $CREATE_IMAGE  ]; then
 
-# Create the image if it doesn't exist or we're not using image cache
-if [ ! -e "$IMAGE_CACHE_FILE.qcow2" -o -z "$IMAGE_CACHE_USE" ] ; then
-    $DIB -x -u -a $ARCH $ALWAYS_ELEMENTS $EXTRA_ELEMENTS -o $IMAGE_CACHE_FILE 2>&1 | tee $IMAGE_CACHE_FILE.log
-else
-    echo "Using cached seed image : $IMAGE_CACHE_FILE"
+    mkdir -p $IMAGE_CACHE_DIR
+    IMAGE_CACHE_FILE=$IMAGE_CACHE_DIR/$(echo $ARCH $ALWAYS_ELEMENTS $EXTRA_ELEMENTS | sha1sum | awk '{ print $1 }' )
+
+    # Create the image if it doesn't exist or we're not using image cache
+    if [ ! -e "$IMAGE_CACHE_FILE.qcow2" -o -z "$IMAGE_CACHE_USE" ] ; then
+        $DIB -x -u -a $ARCH $ALWAYS_ELEMENTS $EXTRA_ELEMENTS -o $IMAGE_CACHE_FILE 2>&1 | tee $IMAGE_CACHE_FILE.log
+    else
+        echo "Using cached seed image : $IMAGE_CACHE_FILE"
+    fi
+
+    sudo cp $IMAGE_CACHE_FILE.qcow2 /var/lib/libvirt/images/$IMAGE_NAME.qcow2
+
+    sudo chattr +C /var/lib/libvirt/images/$IMAGE_NAME.qcow2 || true
 fi
-
-sudo cp $IMAGE_CACHE_FILE.qcow2 /var/lib/libvirt/images/$IMAGE_NAME.qcow2
-
-sudo chattr +C /var/lib/libvirt/images/$IMAGE_NAME.qcow2 || true
 
 if [ $CONFIGURE_VM ]; then
     configure-vm \
