Let cleanup-env only clean a specified environment
devtest_testenv allows the user to specify an environment number. This
will:

 -- Create a seed named seed_$NUM
 -- Create a bridge named brbm$NUM
 -- Create baremetal VMs with names prefixed with baremetalbrbm$NUM

This is used on our CI environment to allow one set of physical nodes to
host several test environments.

Prior to this change, cleanup-env is very insensitive and simply cleans
up all the virsh nodes and disks that it thinks are related to devtest.

This change replicates this logic to allow cleanup-env to clean up only
one specific environment, rather than cleaning up all environments on the
machine.

This is part of a larger plan to make devtest_testenv.sh safe to re-run.
The goal is to be able to cleanup the existing environment and then
create a new environment from scratch. Once this change lands,
devtest_testenv.sh can use cleanup-env to clean up just the specified
environment.

Change-Id: I1b10abda0209f1c58c6c2612542d8a6cd42628e8

diff --git a/scripts/cleanup-env b/scripts/cleanup-env
--- a/scripts/cleanup-env
+++ b/scripts/cleanup-env
@@ -23,16 +23,44 @@ function show_options() {
     echo "Usage: $SCRIPT_NAME"
     echo
     echo "Cleanup vm state left behind by previous runs"
+    echo
+    echo "    -n                     -- Test environment number to clean up."
+    echo "    -o seed_name           -- Name of the seed to clean up."
+    echo "                              If not provided, seed_n will be assumed"
+    echo "                              if -n is used; or simply seed if -n is"
+    echo "                              not provided. "
     exit 1
 }
 
-[ $# -gt 0 ] && show_options
+NUM=
 
-for NAME in $(sudo virsh list --name --all | grep "^\(seed\(.*\|\)\|baremetal\(\|brbm.*\)_.*\)$"); do
+TEMP=$(getopt -o h,n:,o: -n $SCRIPT_NAME -- "$@")
+if [ $? != 0 ] ; then show_options; fi
+
+# Note the quotes around `$TEMP': they are essential!
+eval set -- "$TEMP"
+
+while true ; do
+    case "$1" in
+        -n) NUM="$2" ; shift 2 ;;
+        -o) SEED_NAME="$2" ; shift 2 ;;
+        --) shift ; break ;;
+        *) echo "Error: unsupported option $1." ; show_options ;;
+    esac
+done
+
+if [ -n "$NUM" ]; then
+  SEED_NAME="${SEED_NAME:-seed_${NUM}}"
+  BRIDGE_NAME="brbm${NUM}"
+fi
+SEED_NAME="${SEED_NAME:-seed}"
+
+BAREMETAL_REGEX="baremetal${BRIDGE_NAME}"
+for NAME in $(sudo virsh list --name --all | grep "^\($SEED_NAME\|${BAREMETAL_REGEX}_.*\)$"); do
   sudo virsh destroy $NAME
   sudo virsh undefine --managed-save --remove-all-storage $NAME
 done
 
-for NAME in $(sudo virsh vol-list $LIBVIRT_VOL_POOL 2>/dev/null | grep /var/ | awk '{print $1}' | grep "^\(seed\(.*\|\)|baremetal\(\|brbm.*\)-\)" ); do
+for NAME in $(sudo virsh vol-list $LIBVIRT_VOL_POOL 2>/dev/null | grep /var/ | awk '{print $1}' | grep "^\($SEED_NAME\|$BAREMETAL_REGEX\)" ); do
   sudo virsh vol-delete --pool $LIBVIRT_VOL_POOL $NAME
 done
