Use baremetal element to extract kernel and initrd for undercloud
The "disk-image-get-kernel" is deprecated

Change-Id: I2a61330a26a7bea6abc458781c83ec96f4b604e6

diff --git a/scripts/load-image b/scripts/load-image
--- a/scripts/load-image
+++ b/scripts/load-image
@@ -50,28 +50,31 @@ function remove_image() {
 
 function load_image() {
     FILE=$(readlink -f $1)
+    DIR=$(dirname ${FILE})
+    GLANCE_IMAGE_NAME=$(basename ${FILE%.*})
+    RAMDISK="${DIR}/${GLANCE_IMAGE_NAME}.initrd"
+    KERNEL="${DIR}/${GLANCE_IMAGE_NAME}.vmlinuz"
 
     if [ ! -e "$FILE" ]; then
         echo "Error: specified file $FILE not found"
         exit 1
     fi
+    if [ ! -e "$KERNEL" -o ! -e "$RAMDISK" ] ; then
+        echo "Error: Kernel ($KERNEL) or initrd ($RAMDISK)"
+        echo "       for specified file $FILE not found."
+        echo "       Please verify that the \"baremetal\" element was included during the image built."
+        exit 1
+    fi
 
-    export TMP_IMAGE_DIR=$(mktemp -t -d --tmpdir=${TMP_DIR:-/tmp} image.XXXXXXXX)
-    [ $? -eq 0 ] || die "Failed to create tmp directory"
-    trap cleanup EXIT
-
-    $DIGK -d ${TMP_IMAGE_DIR} -o 'tmp' -i $FILE
-
-    GLANCE_IMAGE_NAME=$(basename ${FILE%.*})
     if [ "$REMOVE_OLD_IMAGES" ]; then
         remove_image "${GLANCE_IMAGE_NAME}-vmlinuz"
         remove_image "${GLANCE_IMAGE_NAME}-initrd"
         remove_image "${GLANCE_IMAGE_NAME}"
     fi
 
-    kernel_id=$(glance image-create --name "${GLANCE_IMAGE_NAME}-vmlinuz" --public --disk-format aki < "$TMP_IMAGE_DIR/tmp-vmlinuz" \
+    kernel_id=$(glance image-create --name "${GLANCE_IMAGE_NAME}-vmlinuz" --public --disk-format aki < "$KERNEL" \
                 | grep ' id ' | awk '{print $4}')
-    ramdisk_id=$(glance image-create --name "${GLANCE_IMAGE_NAME}-initrd"  --public --disk-format ari < "$TMP_IMAGE_DIR/tmp-initrd" \
+    ramdisk_id=$(glance image-create --name "${GLANCE_IMAGE_NAME}-initrd"  --public --disk-format ari < "$RAMDISK" \
                  | grep ' id ' | awk '{print $4}')
 
     # >&3 sends to the original stdout as this is what we are after
@@ -110,13 +113,6 @@ if [ ! "$FILES" ]; then
 fi
 
 which glance >/dev/null || ( echo "Error: unable to locate glance"; exit 1 )
-
-DIB_PATH=${DIB_PATH:-$SCRIPT_HOME/../../diskimage-builder}
-DIGK=$(which disk-image-get-kernel || echo $DIB_PATH/bin/disk-image-get-kernel)
-if [ ! -e $DIGK ]; then
-    echo "Error: unable to locate disk-image-get-kernel"
-    exit 1
-fi
 
 # Attempt to get the OS credentials, or die.
 [ -z "$OS_AUTH_URL" ] && [ -z "$OS_USERNAME" ] && [ -z "$OS_PASSWORD" ] && \
