Remove backwards compatability in setup-baremetal
Now that toci populates the nodes array in the JSON file, the backwards
compatability code in setup-baremetal can die, so gleefully remove it.

Change-Id: I7b8e7b67694319e377df400b122f16bff9e15370

diff --git a/scripts/register-nodes b/scripts/register-nodes
--- a/scripts/register-nodes
+++ b/scripts/register-nodes
@@ -1,31 +1,54 @@
 #!/bin/bash
 set -eu
 
-CPU=$1
-MEM=$2
-DISK=$3
-MACS="$4"
-SERVICE_HOST="$5"
-# Power management settings are optional and only used for real bare metal.
-PM_IPS=( $6 )
-PM_USERS=( $7 )
-PM_PASSWORDS=( $8 )
+if [ -z "$1" ]; then
+    echo "Ironic not supported, please specify service host as the first argument."
+    exit 1
+fi
+if [ -z "$2" ]; then
+    echo "A JSON file of node listing is required"
+    exit 1
+fi
+NODES=$(jq . "$2")
+
+deploy_kernel=$TRIPLEO_ROOT/deploy-ramdisk.kernel
+deploy_ramdisk=$TRIPLEO_ROOT/deploy-ramdisk.initramfs
+deploy_kernel_id=$(glance image-create --name bm-deploy-kernel --public \
+    --disk-format aki < "$deploy_kernel" | awk ' / id / {print $4}')
+deploy_ramdisk_id=$(glance image-create --name bm-deploy-ramdisk --public \
+    --disk-format ari < "$deploy_ramdisk" | awk ' / id / {print $4}')
+
+function cleanup_flavor () {
+    local FLAVOR_NAME=${1:?"cleanup_flavor requires a flavor name"}
+    if nova flavor-show "$FLAVOR_NAME" &> /dev/null; then
+        nova flavor-delete "$FLAVOR_NAME"
+    fi
+}
+
+# While we can't mix hypervisors, having non-baremetal flavors will just
+# confuse things.
+cleanup_flavor 'm1.tiny'
+cleanup_flavor 'm1.small'
+cleanup_flavor 'm1.medium'
+cleanup_flavor 'm1.large'
+cleanup_flavor 'm1.xlarge'
 
 # Ensure nova's baremetal service has fully initialised before proceeding with real nodes
 wait_for 60 10 nova baremetal-node-create devtest_canary 1 1 1 11:22:33:44:55:66
 nova baremetal-node-delete $(nova baremetal-node-list | awk '/devtest_canary/ {print $2}')
 
-count=0
-for MAC in $MACS; do
-
-    if [ -n "${PM_IPS:-}" -a -n "${PM_USERS:-}" -a -n "${PM_PASSWORDS:-}" ]; then
-        nova baremetal-node-create --pm_address=${PM_IPS[$count]} --pm_user=${PM_USERS[$count]} --pm_password=${PM_PASSWORDS[$count]} $SERVICE_HOST $CPU $MEM $DISK $MAC
-    else
-        nova baremetal-node-create $SERVICE_HOST $CPU $MEM $DISK $MAC
-    fi
-
-    count=$((count + 1))
-
+for pos in $(seq 0 $(($(jq length <<< $NODES) - 1))); do
+    cleanup_flavor baremetal${pos}
+    nova flavor-create baremetal${pos} auto $(jq -r ".[$pos][\"memory\"] .[$pos][\"disk\"] .[$pos][\"cpu\"]" <<< $NODES)
+    nova flavor-key baremetal${pos} set "cpu_arch"=$(jq .[$pos][\"arch\"] <<< $NODES) \
+        "baremetal:deploy_kernel_id"="$deploy_kernel_id" \
+        "baremetal:deploy_ramdisk_id"="$deploy_ramdisk_id"
+    id=0 # FIXME
+    nova baremetal-node-create $SERVICE_HOST $(jq -r "\"--pm-addresses=\" + .[$pos][\"pm_addr\"] + \" --pm_user=\" + .[$pos][\"pm_user\"] + \" --pm_password=\" + .[$pos][\"pm_password\"] + " " + .[$pos][\"cpu\"] + " " + .[$pos][\"memory\"] + " " + .[$pos][\"disk\"] + " " + .[$pos][\"mac\"][0]" <<< $NODES)
+    for mac in $(jq .[$pos][\"mac\"] - .[$pos][\"mac\"][0]); do
+        nova baremetal-interface-create $id $mac
+    done
 done
+
 date
 echo "Nodes will be available in 60 seconds from now."
