Remove backwards compatability in setup-baremetal
TripleO CI now populates the nodes array in the JSON datafile, so the
backward compatability code in setup-baremetal can be removed.

As an added bonus, nodes that specify more than one MAC address will
have all of them registered with nova-bm.

Change-Id: I7b8e7b67694319e377df400b122f16bff9e15370

diff --git a/scripts/register-nodes b/scripts/register-nodes
--- a/scripts/register-nodes
+++ b/scripts/register-nodes
@@ -1,31 +1,29 @@
 #!/bin/bash
 set -eu
 
-CPU=$1
-MEM=$2
-DISK=$3
-MACS="$4"
-SERVICE_HOST="$5"
-# Power management settings are optional and only used for real bare metal.
-PM_IPS=( $6 )
-PM_USERS=( $7 )
-PM_PASSWORDS=( $8 )
+SERVICE_HOST=${1:-""}
+if [ -z "$SERVICE_HOST" ]; then
+    echo "Ironic not supported, please specify service host as the first argument."
+    exit 1
+fi
+if [ -z "$2" ]; then
+    echo "A JSON file of node listing is required."
+    exit 1
+fi
+NODES=$(jq . "$2")
 
 # Ensure nova's baremetal service has fully initialised before proceeding with real nodes
 wait_for 60 10 nova baremetal-node-create devtest_canary 1 1 1 11:22:33:44:55:66
 nova baremetal-node-delete $(nova baremetal-node-list | awk '/devtest_canary/ {print $2}')
 
-count=0
-for MAC in $MACS; do
-
-    if [ -n "${PM_IPS:-}" -a -n "${PM_USERS:-}" -a -n "${PM_PASSWORDS:-}" ]; then
-        nova baremetal-node-create --pm_address=${PM_IPS[$count]} --pm_user=${PM_USERS[$count]} --pm_password=${PM_PASSWORDS[$count]} $SERVICE_HOST $CPU $MEM $DISK $MAC
-    else
-        nova baremetal-node-create $SERVICE_HOST $CPU $MEM $DISK $MAC
-    fi
-
-    count=$((count + 1))
-
+node_count=$(($(jq length <<< $NODES) - 1))
+for pos in $(seq 0 $node_count); do
+    NODE_JSON=$(jq ".[$pos]" <<< $NODES)
+    id=$(nova baremetal-node-create $(jq -r "\"--pm_address=\" + .pm_addr + \" --pm_user=\" + .pm_user + \" --pm_password=\\\"\" + .pm_password + \"\\\" $SERVICE_HOST \" + .cpu + \" \" + .memory + \" \" + .disk + \" \" + .mac[0]" <<< $NODE_JSON) | awk '/ id / {print $4}')
+    for mac in $(jq ".[$pos][\"mac\"] - .[$pos][\"mac\"][0]" <<< $NODES); do
+        nova baremetal-interface-add $id $mac
+    done
 done
+
 date
 echo "Nodes will be available in 60 seconds from now."
