Allow set-source-vars to consume a git manifest
This patch allows you to use git manifest files to generate
all the "export DIB_REPO...." commands you would need to be
able to reproduce a build using the same SHA1s as a previous
build.

Change-Id: Ie72ad9697bf790cf13f2335c6290fb1d8ab599fb

diff --git a/scripts/set-source-vars b/scripts/set-source-vars
--- a/scripts/set-source-vars
+++ b/scripts/set-source-vars
@@ -27,6 +27,8 @@ function show_options () {
     echo "            $SCRIPT_NAME -l /my/local/neutron /a/local/nova"
     echo "    e.g. use the url of remote \"origin\" of the locally cloned repositories as input:"
     echo "            $SCRIPT_NAME -r origin /my/local/neutron /a/local/nova"
+    echo "    e.g. use the values from a git manifest:"
+    echo "            $SCRIPT_NAME -m tripleo-git-manifest"
     echo "    The above examples will set the location and reference to use."
     echo "    The reference will be set to the current HEAD reference of the local repository"
     echo
@@ -37,9 +39,10 @@ function show_options () {
     echo "Display source-repositories element environment variables"
     echo
     echo "Options:"
-    echo "    -h, --help                     -- print this help."
-    echo "    -l, --local                    -- use the local path location of the repository"
-    echo "    -r <remote>, --remote <remote> -- remote of the local repo to use to get the repo url"
+    echo "    -h, --help                          -- print this help."
+    echo "    -l, --local                         -- use the local path location of the repository"
+    echo "    -r <remote>, --remote <remote>      -- remote of the local repo to use to get the repo url"
+    echo "    -m <manifest> --manifest <manifest> -- git manifest file as produced by running devtest"
     echo
     echo "Echo the appropriate environment variables to use a local git repository"
     echo "for input into image building via the source-repositories element"
@@ -58,7 +61,7 @@ function show_options () {
     exit $1
 }
 
-TEMP=`getopt -o h,l,n,r: -l help,local,no-echo,no_echo,remote: -n $SCRIPT_NAME -- "$@"`
+TEMP=`getopt -o h,l,n,r:,m: -l help,local,no-echo,no_echo,remote:,manifest: -n $SCRIPT_NAME -- "$@"`
 if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
 # Note the quotes around `$TEMP': they are essential!
@@ -68,26 +71,46 @@ while true ; do
     case "$1" in
         -h|--help) show_options 0 >&2;;
         -l|--local) USE_LOCAL=1; shift 1;;
-        -r|--remote) REMOTE=$2; shift 2;;
+        -r|--remote) USE_REMOTE=1; REMOTE=$2; shift 2;;
+        -m|--manifest-file) USE_MANIFEST=1; MANIFEST=$2; shift 2;;
         --) shift ; break ;;
         *) echo "Error: unsupported option $1." ; exit 1 ;;
     esac
 done
 
-REPOS=( "${@}" )
-
-if (( $# <= 0 )); then echo "Local repository location is required" >&2; show_options 1 >&2; fi
-
 USE_LOCAL=${USE_LOCAL:-0}
+USE_REMOTE=${USE_REMOTE:-0}
 REMOTE=${REMOTE:-""}
+USE_MANIFEST=${USE_MANIFEST:-0}
 
-if [[ "${USE_LOCAL}" == "0" && -z "${REMOTE}" ]] ||\
-    [[ "${USE_LOCAL}" == "1" && -n "${REMOTE}" ]]; then
+if [[ "$((USE_LOCAL + USE_REMOTE + USE_MANIFEST))" != "1" ]]; then
     echo "Choose to either clone the local path (-l)" >&2
     echo "OR" >&2
     echo "to use the remote (-r <remote>) defined in the local repo to lookup the repo URL" >&2
+    echo "OR" >&2
+    echo "to parse repos and SHA1s from a manifest file (-m <manifest-file>)" >&2
     show_options 1 >&2
 fi
+
+transform_manifest() {
+    while read name _type _dest loc ref
+    do
+        name_transformed=$(echo "$name" | tr '[:upper:]-' '[:lower:]_')
+        echo "export DIB_REPOLOCATION_${name_transformed}=$loc"
+        echo "export DIB_REPOREF_${name_transformed}=$ref"
+    done
+}
+
+use_manifest() {
+    if [[ ${USE_MANIFEST} == "1" ]]; then
+        for manifest in "${MANIFEST}"
+        do
+            transform_manifest < ${manifest}
+        done | sort -ut _ -k3
+        exit 0
+    fi
+}
+
 
 get_location() {
     local remote_name=${1:-""}
@@ -122,21 +145,34 @@ get_name() {
     echo $(basename ${name##*:} .git)
 }
 
-declare -A a
+use_repos() {
+    declare -A a
 
-for dir in "${REPOS[@]}"
-do
-    if [[ ! -d ${dir} ]] ; then
-        echo "Not a directory: ${dir}" >&2
-        exit 1
-    fi
-    pushd ${dir} > /dev/null 2>&1
-    REPONAME=$(get_name ${REMOTE})
-    REPONAME_VAR=${REPONAME//[^a-zA-Z0-9]/_}
-    a[DIB_REPOLOCATION_${REPONAME_VAR}]=$(get_location ${REMOTE})
-    a[DIB_REPOREF_${REPONAME_VAR}]=$(get_ref)
-    echo "export DIB_REPOLOCATION_${REPONAME_VAR}=${a[DIB_REPOLOCATION_${REPONAME_VAR}]}"
-    echo "export DIB_REPOREF_${REPONAME_VAR}=${a[DIB_REPOREF_${REPONAME_VAR}]}"
-    popd > /dev/null 2>&1
-done
+    if (( $# <= 0 )); then echo "Local repository location is required" >&2; show_options 1 >&2; fi
+
+    REPOS=( "${@}" )
+
+    for dir in "${REPOS[@]}"
+    do
+        if [[ ! -d ${dir} ]] ; then
+            echo "Not a directory: ${dir}" >&2
+            exit 1
+        fi
+        pushd ${dir} > /dev/null 2>&1
+        REPONAME=$(get_name ${REMOTE})
+        REPONAME_VAR=${REPONAME//[^a-zA-Z0-9]/_}
+        a[DIB_REPOLOCATION_${REPONAME_VAR}]=$(get_location ${REMOTE})
+        a[DIB_REPOREF_${REPONAME_VAR}]=$(get_ref)
+        echo "export DIB_REPOLOCATION_${REPONAME_VAR}=${a[DIB_REPOLOCATION_${REPONAME_VAR}]}"
+        echo "export DIB_REPOREF_${REPONAME_VAR}=${a[DIB_REPOREF_${REPONAME_VAR}]}"
+        popd > /dev/null 2>&1
+    done
+}
+
+
+if [[ "${USE_MANIFEST}" == "1" ]] ; then
+    use_manifest
+else
+    use_repos
+fi
 
