WIP: Fix bashate errors
Change-Id: Id72665aba83df753364940c82db08edcb11e1217
Signed-off-by: Gael Chamoulaud <gchamoul@redhat.com>

diff --git a/scripts/setup-undercloud-passwords b/scripts/setup-undercloud-passwords
--- a/scripts/setup-undercloud-passwords
+++ b/scripts/setup-undercloud-passwords
@@ -36,7 +36,10 @@ function show_options () {
 FILE=
 
 TEMP=`getopt -o hof -l help,overwrite,file -n $SCRIPT_NAME -- "$@"`
-if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+if [ $? != 0 ]; then
+    echo "Terminating..." >&2;
+    exit 1;
+fi
 
 # Note the quotes around `$TEMP': they are essential!
 eval set -- "$TEMP"
@@ -54,8 +57,8 @@ done
 FILE=${FILE:-$1}
 
 if [ -z "$FILE" ]; then
-  echo "ERROR: Must provide a filename"
-  exit 1
+    echo "ERROR: Must provide a filename"
+    exit 1
 fi
 
 OVERWRITE=${OVERWRITE:-""}
