Fix bashate errors
- Excluding awk and python scripts
- Will still fail on scripts/devtest_seed.sh with a 'heredoc did not end
  before EOF at line 419' cause of a bashate bug.

Change-Id: Id72665aba83df753364940c82db08edcb11e1217
Signed-off-by: Gael Chamoulaud <gchamoul@redhat.com>

diff --git a/scripts/setup-overcloud-passwords b/scripts/setup-overcloud-passwords
--- a/scripts/setup-overcloud-passwords
+++ b/scripts/setup-overcloud-passwords
@@ -21,7 +21,7 @@ set -o pipefail
 SCRIPT_NAME=$(basename $0)
 SCRIPT_HOME=$(dirname $0)
 
-function show_options () {
+function show_options {
     echo "Usage: $SCRIPT_NAME [options] FILENAME"
     echo
     echo "Generate passwords for devtest and write them out to a file"
@@ -36,7 +36,10 @@ function show_options () {
 FILE=
 
 TEMP=`getopt -o hof -l help,overwrite,file -n $SCRIPT_NAME -- "$@"`
-if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+if [ $? != 0 ]; then
+    echo "Terminating..." >&2;
+    exit 1;
+fi
 
 # Note the quotes around `$TEMP': they are essential!
 eval set -- "$TEMP"
@@ -54,8 +57,8 @@ done
 FILE=${FILE:-$1}
 
 if [ -z "$FILE" ]; then
-  echo "ERROR: Must provide a filename"
-  exit 1
+    echo "ERROR: Must provide a filename"
+    exit 1
 fi
 
 OVERWRITE=${OVERWRITE:-""}
@@ -67,7 +70,7 @@ if [ -n "$OVERWRITE" ]; then
     echo -n "" > $FILE
 fi
 
-generate_password() {
+function generate_password {
     local name=$1
     if [ -z "$(grep "^$name=" $FILE)" ]; then
         echo "$name=$(os-make-password)" >> $FILE
