Standardise location of environment password/rc files.
Discussion on https://review.openstack.org/#/c/82807 highlighted the fact
that although our scripts consistently write the environment rc files
into $TRIPLEO_ROOT/, the password files are dropped in
whatever directory the user happened to run the scripts from.

Ideally these should be collected into a heat json environment file
which heat can use directly and we can query via jq; as an intermediate
step while we sort that out, this change makes sure that they at least
get written out to $TRIPLEO_ROOT/, alongside the other artifacts we
generate during a devtest run.

write-tripleorc likewise defaulted to creating a tripleorc in whatever
location the user happened to be in at the time, so I've given it
similar treatment to standardise the location of the tripleorc file.

Along the way, stevek objected to having if/then on separate lines. As
the instances in these scripts were 2/3eds of all such occurrences in the
scripts directory, I let my preference for this style override my
preference not to make unrelated stylistic changes in the same commit as
substantive changes.

Change-Id: I30a2cc4f406122bb038d314a277c2444182bd0c9

diff --git a/scripts/setup-undercloud-passwords b/scripts/setup-undercloud-passwords
--- a/scripts/setup-undercloud-passwords
+++ b/scripts/setup-undercloud-passwords
@@ -22,19 +22,20 @@ SCRIPT_NAME=$(basename $0)
 SCRIPT_HOME=$(dirname $0)
 
 function show_options () {
-    echo "Usage: $SCRIPT_NAME [options]"
+    echo "Usage: $SCRIPT_NAME [options] FILENAME"
     echo
     echo "Generate passwords for devtest and write them out to a file"
     echo "that can be sourced."
     echo
     echo "Options:"
-    echo "    -f, --file        -- Specify path for passwords file."
-    echo "                         Defaults to tripleo-undercloud-passwords in the current directory."
+    echo "    -f, --file        -- Noop. For backwards compatibility only"
     echo "    -o, --overwrite   -- Overwrite file if it already exists."
     exit $1
 }
 
-TEMP=`getopt -o hof: -l help,overwrite,file: -n $SCRIPT_NAME -- "$@"`
+FILE=
+
+TEMP=`getopt -o hof -l help,overwrite,file -n $SCRIPT_NAME -- "$@"`
 if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
 # Note the quotes around `$TEMP': they are essential!
@@ -42,21 +43,26 @@ eval set -- "$TEMP"
 
 while true ; do
     case "$1" in
-        -f | --file) FILE=$2; shift 2 ;;
+        -f | --file) shift 1 ;;
         -o | --overwrite) OVERWRITE=--overwrite; shift 1 ;;
-        -h) show_options 0;;
+        -h | --help) show_options 0;;
         --) shift ; break ;;
         *) echo "Error: unsupported option $1." ; exit 1 ;;
     esac
 done
 
-FILE=${FILE:-"tripleo-undercloud-passwords"}
+FILE=${FILE:-$1}
+
+if [ -z "$FILE" ]; then
+  echo "ERROR: Must provide a filename"
+  exit 1
+fi
+
 OVERWRITE=${OVERWRITE:-""}
 
 # Don't overwrite $FILE if it already exists and the overwrite option
 # wasn't provided.
-if [ -f $FILE -a -z "$OVERWRITE" ]
-then
+if [ -f $FILE -a -z "$OVERWRITE" ]; then
     echo $FILE exists, not overwriting.
     echo Either delete the file first, or specify -o
     exit 0
