Configure a root disk & ephemeral disk for baremetal nodes
The current NODE_DISK variable (or disk option in testenv.json file)
specifies the size of the disk at our disposal. Add new ROOT_DISK
variable that specifies the size of the root partition on the the disk
and we then calculate and assign the remaining disk space to the
epheramal disk that will store all persistent data for baremetal nodes.

Change-Id: I1a941e1120fd4091311b7f80e145c47715ec2465

diff --git a/scripts/setup-baremetal b/scripts/setup-baremetal
--- a/scripts/setup-baremetal
+++ b/scripts/setup-baremetal
@@ -98,7 +98,15 @@ MEM=$(jq -r ".[0][\"memory\"]" <<< $NODES)
 DISK=$(jq -r ".[0][\"disk\"]" <<< $NODES)
 CPU=$(jq -r ".[0][\"cpu\"]" <<< $NODES)
 ARCH=$(jq -r ".[0][\"arch\"]" <<< $NODES)
-nova flavor-create baremetal auto $MEM $DISK $CPU
+
+EPHEMERAL_DISK=$(( $DISK - $ROOT_DISK ))
+if (( $EPHEMERAL_DISK < 0 )); then
+    echo "Error: NODE_DISK - ROOT_DISK must be >= 0 to specify size of ephemeral disk"
+    exit 1
+fi
+
+nova flavor-create baremetal \
+    --ephemeral $EPHEMERAL_DISK auto $MEM $ROOT_DISK $CPU
 nova flavor-key baremetal set "cpu_arch"="$ARCH" \
     "baremetal:deploy_kernel_id"="$deploy_kernel_id" \
     "baremetal:deploy_ramdisk_id"="$deploy_ramdisk_id"
