Standardise location of environment password files.
Discusion on https://review.openstack.org/#/c/82807 highlighted the fact
that although our scripts consistently write the environment rc files
into $TRIPLEO_ROOT/, the password files are dropped in
whatever directory the user happened to run the scripts from.

Ideally these should be collected into a heat json environment file
which heat can use directly and we can query via jq; as an intermediate
step while we sort that out, this change makes sure that they at least
get written out to $TRIPLEO_ROOT/, alongside the other artifacts we
generate during a devtest run.

Along the way, stevek objected to having if/then on seperate lines. As
the instances in these scripts were 2/3eds of all such occurences in the
scripts directory, I let my preference for this style override my
preference not to make unrelated stylistic changes in the same commit as
substantive changes.

Change-Id: I30a2cc4f406122bb038d314a277c2444182bd0c9

diff --git a/scripts/setup-undercloud-passwords b/scripts/setup-undercloud-passwords
--- a/scripts/setup-undercloud-passwords
+++ b/scripts/setup-undercloud-passwords
@@ -29,11 +29,11 @@ function show_options () {
     echo
     echo "Options:"
     echo "    -f, --file        -- Specify path for passwords file."
-    echo "                         Defaults to tripleo-undercloud-passwords in the current directory."
     echo "    -o, --overwrite   -- Overwrite file if it already exists."
     exit $1
 }
 
+FILE=""
 TEMP=`getopt -o hof: -l help,overwrite,file: -n $SCRIPT_NAME -- "$@"`
 if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
@@ -50,16 +50,27 @@ while true ; do
     esac
 done
 
-FILE=${FILE:-"tripleo-undercloud-passwords"}
+if [-z "$FILE" ]; then
+  echo "ERROR: Must provide a filename"
+  exit 1
+fi
+
 OVERWRITE=${OVERWRITE:-""}
 
 # Don't overwrite $FILE if it already exists and the overwrite option
 # wasn't provided.
-if [ -f $FILE -a -z "$OVERWRITE" ]
-then
+if [ -f $FILE -a -z "$OVERWRITE" ]; then
     echo $FILE exists, not overwriting.
     echo Either delete the file first, or specify -o
     exit 0
+fi
+
+OLDFILE=tripleo-undercloud-passwords
+if [ -f "$OLDFILE" ]; then
+  echo Relocating $OLDFILE to $FILE
+  mv $OLDFILE $FILE
+  ln -s $FILE $OLDFILE
+  exit 0
 fi
 
 touch $FILE
