Add mechanism for wait_for command to bail out on an unrecoverable error
devtest will wait for a long time (3000 seconds for an overcloud) even
if the stack has failed and will never be ready.

This patch updates wait_for so that if the COMMAND fails with a status
greater then 1 then we exit the wait_for command with a error status of 1
notifying the user.

Updated stack-ready to use this. If the stack status becomes CREATE_FAILED
then we exit with status 2 exiting the long wait_for loop.

Change-Id: Iac0d49754e2a7059784ca29773056e13b42ad88a

diff --git a/scripts/stack-ready b/scripts/stack-ready
--- a/scripts/stack-ready
+++ b/scripts/stack-ready
@@ -28,6 +28,11 @@ STACK_STATUS=$(heat stack-show $STACK_NAME | awk '/ stack_status / { print $4 }'
 
 if [ "CREATE_COMPLETE" = "$STACK_STATUS" -o "UPDATE_COMPLETE" = "$STACK_STATUS" ]; then
     exit 0
+elif [ "CREATE_FAILED" = "$STACK_STATUS" ]; then
+    # The stack will never be ready so notify the wait_for command of this
+    echo "The stack has failed to start and will never be ready."
+    echo "STACK_STATUS=$STACK_STATUS"
+    exit 2
 else
     exit 1
 fi
diff --git a/scripts/wait_for b/scripts/wait_for
--- a/scripts/wait_for
+++ b/scripts/wait_for
@@ -50,7 +50,15 @@ fi
 i=0
 while [ $i -lt $LOOPS ]; do
     i=$((i + 1))
-    OUTPUT=$(eval $COMMAND) && exit 0 || true
+    OUTPUT=$(eval $COMMAND) && exit 0
+    STATUS=$?
+    if [ $STATUS -gt 1 ]; then
+        echo "Comand failed with status greater then 1. Not waiting for it."
+        echo "COMAND=$COMMAND"
+        echo "EXIT STATUS=$STATUS"
+        echo "OUTPUT=$OUTPUT"
+        exit 1
+    fi
     sleep $SLEEPTIME
 done
 SECONDS=$((LOOPS * SLEEPTIME))
