WIP - Move wait_for for checking exit status to checking for condition to be true
This is Work In Progress. It is built on top of
https://review.openstack.org/#/c/76240

Note: this contains a bunch of echo statements that need to be removed,
or improved and good general tidy up but please ignore that for now so that
we can concentrate on how wait_for should work. Also if accepted part of this
will have to be moved back into Dan's review above.

Details:

- add ENV SUCCESSFUL_MATCH_OUTPUT that is a regular expression that wait_for
  waits till the command matches. At which point wait_for exits 0 telling the
  calling script to continue.

- wait_for fails back to checking exit status's if SUCCESSFUL_MATCH_OUTPUT is
  not set.

- Remove stack-ready script as this is using both exit status and the new
  EXIT_MATCH_OUTPUT that checks output. This required adding a
  "echo PRIVATE_MESSAGE".

- Add a wait_for_stack_ready that calls wait with heat directly. It also
  removes the dependency on the exit status's completely from the wait_for
  and can be maintained independently of who is using the script.

- wait_for_stack_ready also shows developers for to use wait_for ENV variables.

- Developers can see in wait_for_stack_ready how to use the wait_for correctly

Change-Id: I7daf5010d15e458d98698fb8b7e744e2a17596b1

diff --git a/scripts/wait_for b/scripts/wait_for
--- a/scripts/wait_for
+++ b/scripts/wait_for
@@ -45,6 +45,7 @@ function show_options() {
 LOOPS=${1:-""}
 SLEEPTIME=${2:-""}
 FAIL_MATCH_OUTPUT=${FAIL_MATCH_OUTPUT:-""}
+SUCCESSFUL_MATCH_OUTPUT=${SUCCESSFUL_MATCH_OUTPUT:-""}
 shift 2 || true
 COMMAND="$@"
 
@@ -52,15 +53,35 @@ if [ -z "$LOOPS" -o -z "$SLEEPTIME" -o -z "$COMMAND" ]; then
     show_options
 fi
 
+# Backwards compatibility. If we don't have a SUCCESSFUL_MATCH_OUTPUT variable
+# set then revert back to waiting for the command to successfully succeed.
+BACKWARDS_COMPAT=
+if [ -z "$SUCCESSFUL_MATCH_OUTPUT" ]; then
+    BACKWARDS_COMPAT=1
+fi
 
 i=0
 while [ $i -lt $LOOPS ]; do
     i=$((i + 1))
-    OUTPUT=$(eval $COMMAND 2>&1) && exit 0 || true
-    if [[ -n "$FAIL_MATCH_OUTPUT" ]] && [[ $OUTPUT =~ $FAIL_MATCH_OUTPUT ]]; then
+    STATUS=0
+    OUTPUT=$(eval $COMMAND 2>&1) || STATUS=$?
+    if [[ $STATUS -ne 0 ]]; then
+        # We always retry on command failure
+        echo "Retry command, command failed $STATUS"
+    elif [[ -n "$SUCCESSFUL_MATCH_OUTPUT" ]] \
+        && [[ $OUTPUT =~ $SUCCESSFUL_MATCH_OUTPUT ]]; then
+        # print the output so that the user can work with this in the future.
+        echo "$OUTPUT"
+        exit 0
+    elif [[ -n "$FAIL_MATCH_OUTPUT" ]] \
+        && [[ $OUTPUT =~ $FAIL_MATCH_OUTPUT ]]; then
         echo "Command output matched '$FAIL_MATCH_OUTPUT'. Exiting..."
         exit 1
+    elif [[ -n "$BACKWARDS_COMPAT" ]] && [[ $STATUS -eq 0 ]]; then
+        # The successfully completed.
+        exit 0
     fi
+
     sleep $SLEEPTIME
 done
 SECONDS=$((LOOPS * SLEEPTIME))
