Make wait_for use getopt and add walltime support
We currently use wait_for which does not account for time spent blocking
during COMMAND. This leads to issues where it is hard to calculate time
we want to spend waiting for something. Modifying wait_for and
wait_for_stack_ready to support walltime based timeouts.

Closes-Bug: #1407132

Change-Id: Icdc626ef8075fbd2f9e7cb7c011a12351c815e09

diff --git a/scripts/wait_for b/scripts/wait_for
--- a/scripts/wait_for
+++ b/scripts/wait_for
@@ -17,47 +17,126 @@
 
 set -e  # exit on the first non-zero status
 set -u  # exit on unset variables
+set -o pipefail
 
 SCRIPT_NAME=$(basename $0)
 
 
 function show_options() {
-    echo "Usage: $SCRIPT_NAME LOOPS_NUMBER SLEEP_TIME ARGS"
+    EXITVAL=${1:-1}
+    echo "Usage: $SCRIPT_NAME [-wlh] [-w TIMEOUT] [-l LOOP_COUNT] [-f FAIL_MATCH] [-s SUCCESS_MATCH] --delay SLEEP_TIME -- COMMAND"
     echo
-    echo "ARGS are read and concatenated together into a single command."
-    echo "Execute the command in a loop until it succeeds or the number"
-    echo "of attempts exceeds LOOPS_NUMBER value. After each failure"
-    echo "pause for SLEEP_TIME seconds."
+    echo "Waits for a command to fail, succeed, or timeout."
     echo
-    echo "An optional FAIL_MATCH_OUTPUT variable may also be set to control "
-    echo "if the loop exits early if the commands stdout/stderr matches the "
-    echo "supplied regex string."
+    echo "Options:"
+    echo "      -h,--help                   -- this help"
+    echo "      -w,--walltime TIMEOUT       -- Timeout after TIMEOUT seconds."
+    echo "      -l,--looptimeout LOOP_COUNT -- Timeout after checking COMMAND LOOP_COUNT times."
+    echo "      -d,--delay SLEEP_TIME       -- Seconds to sleep between checks of COMMAND."
+    echo "      -s,--success-match          -- Output that indicates a success."
+    echo "      -f,--fail-match             -- Output that indicates a short-circuit failure."
+    echo
+    echo "Execute the command in a loop until it succeeds, a timeout is reached, or"
+    echo "a short-circuit failure occurs. Between each check of the command sleep for"
+    echo "the number of seconds specified by SLEEP_TIME."
     echo
     echo "Examples:"
-    echo "    wait_for 30 10 ping -c 1 192.0.2.2"
-    echo "    wait_for 10 1 ls file_we_are_waiting_for"
-    echo "    wait_for 10 3 date \| grep 8"
-    echo "    FAIL_MATCH_OUTPUT=CREATE_FAILED wait_for 30 10 heat stack-show undercloud"
-    echo "    SUCCESSFUL_MATCH_OUTPUT=CREATE_COMPLETE wait_for 30 10 heat stack-show undercloud"
-    exit 1
+    echo "    wait_for -w 300 --delay 10 -- ping -c 1 192.0.2.2"
+    echo "    wait_for -w 10 --delay 1 -- ls file_we_are_waiting_for"
+    echo "    wait_for -w 30 --delay 3 -- date \| grep 8"
+    echo "    wait_for -w 300 --delay 10 --fail-match CREATE_FAILED -- heat stack-show undercloud"
+    echo "    wait_for -w 300 --delay 10 --success-match CREATE_COMPLETE -- heat stack-show undercloud"
+    exit $EXITVAL
 }
 
+USE_WALLTIME=
+TIMEOUT=
+DELAY=
 
-LOOPS=${1:-""}
-SLEEPTIME=${2:-""}
-FAIL_MATCH_OUTPUT=${FAIL_MATCH_OUTPUT:-""}
+if [ -n "${SUCCESSFUL_MATCH_OUTPUT:-}" ]; then
+    echo "DEPRECATION WARNING: Using env vars for specifying SUCCESSFUL_MATCH_OUTPUT is deprecated."
+fi
 SUCCESSFUL_MATCH_OUTPUT=${SUCCESSFUL_MATCH_OUTPUT:-""}
-shift 2 || true
+if [ -n "${FAIL_MATCH_OUTPUT:-}" ]; then
+    echo "DEPRECATION WARNING: Using env vars for specifying FAIL_MATCH_OUTPUT is deprecated."
+fi
+FAIL_MATCH_OUTPUT=${FAIL_MATCH_OUTPUT:-""}
+
+USE_ARGPARSE=0
+# We have to support positional arguments for backwards compat
+if [ -n "$1" -a "${1:0:1}" == "-" ]; then
+    USE_ARGPARSE=1
+else
+    echo "DEPRECATION WARNING: Using positional arguments for wait_for is deprecated."
+fi
+
+if [ $USE_ARGPARSE -eq 1 ]; then
+    set +e
+    TEMP=$(getopt -o h,w:,l:,d:,s:,f: -l help,walltime:,looptimeout:,delay:,success-match:,fail-match: -n $SCRIPT_NAME -- "$@")
+    if [ $? != 0 ] ; then show_options ; fi
+    set -e
+
+    # Note the quotes around `$TEMP': they are essential!
+    eval set -- "$TEMP"
+
+    while true ; do
+        case "$1" in
+            -h) show_options 0;;
+            --help) show_options 0;;
+            -w) [ -n "$USE_WALLTIME" ] && show_options
+                USE_WALLTIME=1
+                TIMEOUT="$2"
+                shift 2
+                ;;
+            --walltime) [ -n "$USE_WALLTIME" ] && show_options
+                USE_WALLTIME=1
+                TIMEOUT="$2"
+                shift 2
+                ;;
+            -l) [ -n "$USE_WALLTIME" ] && show_options
+                USE_WALLTIME=0
+                TIMEOUT="$2"
+                shift 2
+                ;;
+            --looptimeout) [ -n "$USE_WALLTIME" ] && show_options
+                USE_WALLTIME=0
+                TIMEOUT="$2"
+                shift 2
+                ;;
+            -d) DELAY="$2"; shift 2;;
+            --delay) DELAY="$2"; shift 2;;
+            -s) SUCCESSFUL_MATCH_OUTPUT="$2"; shift 2;;
+            --success-match) SUCCESSFUL_MATCH_OUTPUT="$2"; shift 2;;
+            -f) FAIL_MATCH_OUTPUT="$2"; shift 2;;
+            --fail-match) FAIL_MATCH_OUTPUT="$2"; shift 2;;
+            --) shift ; break ;;
+        esac
+    done
+else
+    TIMEOUT=${1:-""}
+    DELAY=${2:-""}
+    USE_WALLTIME=0
+    shift 2 || true
+fi
+
 COMMAND="$@"
 
-if [ -z "$LOOPS" -o -z "$SLEEPTIME" -o -z "$COMMAND" ]; then
+if [ -z "$TIMEOUT" -o -z "$DELAY" -o -z "$COMMAND" ]; then
     show_options
 fi
 
 
-i=0
-while [ $i -lt $LOOPS ]; do
-    i=$((i + 1))
+ENDTIME=$(($(date +%s) + $TIMEOUT))
+TIME_REMAINING=0
+function update_time_remaining() {
+    CUR_TIME="$(date +%s)"
+    TIME_REMAINING=$(($ENDTIME - $CUR_TIME))
+}
+
+
+OUTPUT=
+
+function check_cmd() {
     STATUS=0
     OUTPUT=$(eval $COMMAND 2>&1) || STATUS=$?
     if [[ -n "$SUCCESSFUL_MATCH_OUTPUT" ]] \
@@ -72,10 +151,40 @@ while [ $i -lt $LOOPS ]; do
         # it's output so we have finished waiting.
         exit 0
     fi
+}
 
-    sleep $SLEEPTIME
+i=0
+while [ $USE_WALLTIME -eq 1 -o $i -lt $TIMEOUT ]; do
+    if [ $USE_WALLTIME -eq 1 ]; then
+        update_time_remaining
+        if [ $TIME_REMAINING -le 0 ]; then
+            break
+        fi
+    else
+        i=$((i + 1))
+    fi
+
+    check_cmd
+
+    if [ $USE_WALLTIME -eq 1 ]; then
+        update_time_remaining
+        if [ $TIME_REMAINING -lt $DELAY ]; then
+            if [ $TIME_REMAINING -gt 0 ]; then
+                sleep $TIME_REMAINING
+                check_cmd
+            fi
+        else
+            sleep $DELAY
+        fi
+    else
+        sleep $DELAY
+    fi
 done
-SECONDS=$((LOOPS * SLEEPTIME))
+if [ $USE_WALLTIME -eq 1 ]; then
+    SECONDS=$TIMEOUT
+else
+    SECONDS=$((TIMEOUT * DELAY))
+fi
 printf 'Timing out after %d seconds:\nCOMMAND=%s\nOUTPUT=%s\n' \
     "$SECONDS" "$COMMAND" "$OUTPUT"
 exit 1
