Cause wait_for heat stack-create fail fast
Add a script called wait_for_stack_ready that calls heat stack-show in a
wait_for loop waiting for either the stack to be ready or else when the stack
fails and will never be ready.

wait_for_stack_ready sets up the FAIL_MATCH_OUTPUT environment variable to
check when stack-create fails and setups a new SUCCESSFUL_MATCH_OUTPUT that
check the output from the heat stack-show for when the stack reaches the
UPDATE_COMPLETE or CREATE_COMPLETE state.

Change-Id: I7daf5010d15e458d98698fb8b7e744e2a17596b1

diff --git a/scripts/wait_for b/scripts/wait_for
--- a/scripts/wait_for
+++ b/scripts/wait_for
@@ -37,7 +37,8 @@ function show_options() {
     echo "    wait_for 30 10 ping -c 1 192.0.2.2"
     echo "    wait_for 10 1 ls file_we_are_waiting_for"
     echo "    wait_for 10 3 date \| grep 8"
-    echo "    FAIL_MATCH_OUTPUT=CREATE_FAILED wait_for 30 10 stack-ready undercloud"
+    echo "    FAIL_MATCH_OUTPUT=CREATE_FAILED wait_for 30 10 heat stack-show undercloud"
+    echo "    SUCCESSFUL_MATCH_OUTPUT=CREATE_COMPLETE wait_for 30 10 heat stack-show undercloud"
     exit 1
 }
 
@@ -45,6 +46,7 @@ function show_options() {
 LOOPS=${1:-""}
 SLEEPTIME=${2:-""}
 FAIL_MATCH_OUTPUT=${FAIL_MATCH_OUTPUT:-""}
+SUCCESSFUL_MATCH_OUTPUT=${SUCCESSFUL_MATCH_OUTPUT:-""}
 shift 2 || true
 COMMAND="$@"
 
@@ -56,11 +58,21 @@ fi
 i=0
 while [ $i -lt $LOOPS ]; do
     i=$((i + 1))
-    OUTPUT=$(eval $COMMAND 2>&1) && exit 0 || true
-    if [[ -n "$FAIL_MATCH_OUTPUT" ]] && [[ $OUTPUT =~ $FAIL_MATCH_OUTPUT ]]; then
+    STATUS=0
+    OUTPUT=$(eval $COMMAND 2>&1) || STATUS=$?
+    if [[ -n "$SUCCESSFUL_MATCH_OUTPUT" ]] \
+        && [[ $OUTPUT =~ $SUCCESSFUL_MATCH_OUTPUT ]]; then
+        exit 0
+    elif [[ -n "$FAIL_MATCH_OUTPUT" ]] \
+        && [[ $OUTPUT =~ $FAIL_MATCH_OUTPUT ]]; then
         echo "Command output matched '$FAIL_MATCH_OUTPUT'. Exiting..."
         exit 1
+    elif [[ -z "$SUCCESSFUL_MATCH_OUTPUT" ]] && [[ $STATUS -eq 0 ]]; then
+        # The command successfully completed and we aren't testing against
+        # it's output so we have finished waiting.
+        exit 0
     fi
+
     sleep $SLEEPTIME
 done
 SECONDS=$((LOOPS * SLEEPTIME))
