WIP: Fix bashate errors
Change-Id: Id72665aba83df753364940c82db08edcb11e1217
Signed-off-by: Gael Chamoulaud <gchamoul@redhat.com>

diff --git a/scripts/write-tripleorc b/scripts/write-tripleorc
--- a/scripts/write-tripleorc
+++ b/scripts/write-tripleorc
@@ -21,7 +21,7 @@ set -o pipefail
 SCRIPT_NAME=$(basename $0)
 SCRIPT_HOME=$(dirname $0)
 
-function show_options () {
+function show_options {
     echo "Usage: $SCRIPT_NAME [options] FILENAME"
     echo
     echo "Write devtest defined environment variables to a file."
@@ -38,7 +38,10 @@ function show_options () {
 FILE=
 
 TEMP=`getopt -o hof -l help,overwrite,file -n $SCRIPT_NAME -- "$@"`
-if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+if [ $? != 0 ]; then
+    echo "Terminating..." >&2;
+    exit 1;
+fi
 
 # Note the quotes around `$TEMP': they are essential!
 eval set -- "$TEMP"
@@ -56,8 +59,8 @@ done
 FILE=${FILE:-$1}
 
 if [ -z "$FILE" ]; then
-  echo "ERROR: Must provide a filename"
-  exit 1
+    echo "ERROR: Must provide a filename"
+    exit 1
 fi
 
 OVERWRITE=${OVERWRITE:-""}
